# Generated by Django 5.1.2 on 2025-01-01 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('sport', models.CharField(max_length=100)),
                ('teamName', models.CharField(max_length=100)),
                ('scheduleLink', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameDateTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameDateTime', models.DateTimeField()),
                ('leagueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Leagues_id', to='prs_scheduler.leagues')),
            ],
        ),
    ]
